version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
    networks:
      - toy-workshop-network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - toy-workshop-network

networks:
  toy-workshop-network:
